repos:
-   repo: local
    hooks:
    -   id: exclude-unwanted
        name: exclude unwanted files, e.g. training data
        entry: exclude unwanted files, e.g. training data
        language: fail
        files: '.*xlsx|.*dcm|.*pyc'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: detect-private-key
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: mixed-line-ending
    -   id: debug-statements
    -   id: pretty-format-json
    -   id: end-of-file-fixer
        args: ['--autofix']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [
#            flake8-bandit,
            flake8-blind-except,
            flake8-breakpoint,
            flake8-broken-line,
            flake8-bugbear,
            flake8-builtins,
            flake8-class-newline,
            flake8-comprehensions,
#            flake8-debugger,
#            flake8-eradicate,
#            flake8-logging-format,
#            flake8-pep3101,
#            flake8-polyfill,
#            flake8-quotes,
#            flake8-string-format,
            flake8-type-annotations,
#            flake8-use-fstring,
#            flake8-fixme,
            flake8-markdown,
            flake8-2020,
#            flake8-print,
#            pep8-naming
             ]
        args: ['--max-line-length=160', '--ignore=E121,E123,E125,E501,F401,F403,W503']

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0  # Use the ref you want to point at
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-no-log-warn
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']
